### ISSUE TITLE
DE - update DE XML export to v4.3

### ISSUE THREAD

**Issue by KeeganW** [TeselaGen/ve#10]
Nathan Hillson:
The DE XML schema has been updated to v4.3.

The main differences are new fields for linking the part sources with entries in ICE: 
```xml
<xs:element ref="de:icePartId" minOccurs="0" />
<xs:element ref="de:iceEntryURI" minOccurs="0" />
<xs:element name="iceEntryURI" type="xs:string" />
```

I am attaching the new schema and a new design file. Note that the example file is essentially the same as before except for the version number because the design in the example doesn't have any parts that were mapped from ICE-tethered VE.

When updating the DE XML import process, note that you should retain the ability to open previous versions of the files (e.g. v4.2) in addition to the most recent one.

[Documents](https://drive.google.com/a/teselagen.com/folderview?id=0B7Qtc_l6JJJvUWtMM0JldVRycUU&usp=drive_web)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#60
