### ISSUE TITLE
Warning messages on import of sequences can be improved for clarity... has become a request to improve sequence parser

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1137]
After QA for ticket #917 

Note that warning messages are sometimes confusing/incorrect. Here are two examples:

This one is has incorrect message in header.
![image](https://cloud.githubusercontent.com/assets/7561861/8289634/9945dfba-18d2-11e5-8f66-f2896a7c6b1d.png)

This one is confusing, since most folks will not see numbers and will see "imported successfully"
![image](https://cloud.githubusercontent.com/assets/7561861/8289668/c66ea9b8-18d2-11e5-8519-3c74aacfd767.png)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#50
