### ISSUE TITLE
Sequence Provenance Tracking – keeping track of where DNA came from

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1253]
This is a big one, and will require the inclusion of a system of provenance tracking so that any DNA sequence record created in the system will have parental identifiers that link it to its ancestors. Some characteristics of the provenance tracking system are:
* A record of the node (the sequence id) and the edge (parent-child link) is kept.
* Sequence records do not need to represent actual DNA stored in the lab (differentiation flag between real sequences and those that are only *in silico*)
* Must track all the parents from which the sequence was constructed
* A sequence can have no parents. In that case it becomes a top level node.
* The provenance graph must be an directed acyclic graph (DAG – no loops so your child can not be your parent)

See the [Requirements Document](https://docs.google.com/document/d/13ndQ5fuTFbORcBOmzbIjI_sKQiExsqmHvtOZWe2Bwgo/edit#) for more detail!

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#42
