### ISSUE TITLE
Integrate Restriction Enzyme Library

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1262]
Extensible library of enzymes used to cut DNA. The extensibility is what we need to work on, allowing the user (or an admin?) to upload new sets of enzymes.
* accessible via VE --> Tools (done)
* allow custom sets for display in VE
* allow vendor catalog sets
* display DNA gel simulation (done, perhaps need to update functionality for partial cuts)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#84
