### ISSUE TITLE
TAP: Tox/Allergy/Pathogen Screen

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1267]
In-app functionality to check genes for pathogenicity/allergenicity/toxicity using existing resources.
* High importance to DAS
* Results and the detail folder link currently are emailed to the submitter and cc the mailing list .DL BIOS DLBIOS@dow.com 
* Primary input is a FASTA file containing AA sequence. Should allow for DNA sequence input in the future.
* Log files currently associate run information with Project / Project Leader / Project Description / Assessment Purpose (Biosafety or Regulatory)
* Pathogenicity check (not yet required at DAS)
  * Check against synthesis of pathogenic sequences. This is not required at DAS, but a review of current practices as gene synthesis companies and recommendation for future checks should be made.
* Allergenicity check
  * FASTA search against internal instance of the Nebraska Allergenicity Database
  * Returns hit value of 0 or 1, positive hits have associated information on Allergen source / type / group
  * Interesting note: sucrose binding proteins are often allergens
* Toxicity check
  * FASTA search against internally curated list of AA sequences cited in literature containing keywords such as “toxic” or “toxicity”
  * Returns AA sequence if there is a DB hit (otherwise null) and an xls file containing a table of accession numbers, FASTA statistics, and URLs to a amino acid profiles on uniprot.org where the publication can be found, users are then required to read the publications to assess the toxicity risk(s) of the protein in question.
  * Internally curated DB has not been updated in a few years, unclear what the curation/update for this DB is.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#80
