### ISSUE TITLE
BLAST - Ability to BLAST search the Datasphere

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1268]
In Phase I TeselaGen will replicate the current functionality found in DesignDB/PlasmidDB to export data from Peony in a way suitable for the genomics group to create a BLAST database. The TeselaGen development plan also calls for a BLAST implementation similar to one found in various desktop tools. This implementation will come in the course of normal Peony private cloud updates but is not required in Phase I.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#79
