### ISSUE TITLE
Sequencing Primer Design utility for generating sequencing primers

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1269]
* Supporting Materials:
  * [Sequencing PPT](https://drive.google.com/open?id=0B_l-WxHozfYhS1lKSlpRTEZPWGM) from Scott Bevan
  * [Primer Design scripts](https://drive.google.com/file/d/0B_l-WxHozfYhdm11em5iclFWdGc/view?usp=drive_web) by Hank Wu via Bill Moskal 
* Goal: primers that are spaced at regular intervals to generate data for a large piece of DNA
* Need to design primers on both strands of the DNA
* Existing tools: Primer3 (also used by j5)
* Steps (from Vector NTI):
  * Select the portion of the sequence for which you would like to design primers
  * Specify a window size (ideal spacing between primers)
  * Specify parameters (length, GC content, etc.) – normally use the same parameters every time 
  * Specify the strand – would be nice to do either strand or both strands at once
  * Specify the number of primers per window – we almost always want one primer
  * Click okay (primers are designed)
  * Name the primers and save them to your database (very poorly implemented in VNTI)
  * Examine the sequence immediately adjacent to (upstream of) each window
  * If this sequence matches the parameters set by the user, it becomes a primer
  * If the sequence doesn’t match the parameters, move one base pair at a time until a sequence that matches the parameter is found
  * Scott would prefer to look inside the window rather than outside “(this is a “next level” need)”
  * Scott would “really prefer a checkbox to select either strategy”
* If you have a set of combinatorially created plasmids, you can use the same primers to sequence multiple plasmids → Two workflows:
  * Low/medium throughput:
    * Primers are expensive ($4.50 each)
    * Must re-use existing primers to be cost efficient
    * When sequencing a new plasmid, we need a tool to identify suitable existing primers and to fill gaps with new primer synthesis
  * High throughput
    * Primers are cheap at bulk pricing ($1.40)
    * Use a primer once and throw it away
    * Design a new set of primers for the next plasmid (primer reuse is a non issue)
    * LIMS capabilities need to be enhanced to keep track of primers/sequences etc (Phase II?) Currently using RCC/Penelope/Olaf
    * RefID/sequences/PCRproducts/Clones/PCRscreen/Sequence/Primers/ → genoread validated targets move one, others must be reworked.
    * Currently using [Primer Design scripts](https://drive.google.com/file/d/0B_l-WxHozfYhdm11em5iclFWdGc/view?usp=drive_web) by Hank Wu via Bill Moskal
  * Note ‘Difficulties in Reusing Primers’ in the [PPT from Scott Bevan](https://drive.google.com/open?id=0B_l-WxHozfYhS1lKSlpRTEZPWGM)
* Contact: Scott Bevan, David Mann

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#78
