### ISSUE TITLE
COC/IP/BMRF Rule checker

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1270]
Automatically annotate sequence as adhering to COC rules and if sequence is licensed (IP Status).
* Checks sequence against COC rules and generates appropriate reports or flags.
* In Phase I, Peony will have interfaces for:
  * Pathogenicity, Allergenicity, Toxicity checks that populate fields indicating the sequence has passed pathogenicity, allergenicity and toxicity tests (see PAT above).
  * Preferred sequence check that populates a field indicating that this sequence is found in the preferred sequence database.
  * IP landscape check that populates a field identifying licensing status of gene (sometimes expires). Likely to pull info from an existing licensing database).
* In addition, there are fields that will need to be added to the sequence table to accommodate business rules, flags and values. These fields will be added to the table definition and are derived from the [COC rules questionnaire](https://docs.google.com/spreadsheets/d/1_uY3cX-5jrBajxrg8anNgjpmHoBfK-YVSroZgXwU_MY/edit#gid=63297238)
* Contact: Scott Bevan on COC rule checks
* Contact: Steve Webb on licences

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#77
