### ISSUE TITLE
Parent/Child Lineage Tracking and Repair

### ISSUE THREAD

**Issue by sampearl** [TeselaGen/ve#1271]
Automatically track, visualize, and repair  parent/child relationships; when a “sequence error” is discovered (data stored vs. observed in sample), corrections can be made to the sequence data and the corresponding downstream lineage of sequences.

1. Lineage Tracking
   * Table View
   * Graphical View
2. Repair Lineage (see Meghan’s story)
   * User confirms a “sequence error”
   * Step upwards in parent lineage and sequence samples to determine the first appearance of the error 
   * Propagate base-pair changes to all PCR’d dependent lineage
   * Inform other users of sequence changes and parental sequence changes
   * Notebooks do not change
   * Selectable markers and reporters like YFP are high priority and must be repaired as soon as discovered 
   * Contact: Scott or Sarah

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#76
