### ISSUE TITLE
Home: Create Sequence dialog should be named 'Create Sequence' not 'Name'

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1387]
Starting from My Sequences + button or from Home: Create Sequence button, modal window should be same as route taken if you hit the My Sequences + button. Why short-circuit the new dialog? When you do get to the naming window... the window name should not be "Name" but should reflect what link rasied the window... so "Create Sequence" or "Create New Blank Sequence" should be used instead of "Name". "Name" is more appropriate as a field name not a window name.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#107
