### ISSUE TITLE
Rationalize right-click menu for all library views

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1390]
We should rationalize the right-click menu across all  library views. Menu items specific to a particular library can sit below a separator.

My Protocols: Rename, Edit, Delete, Create Copy, Export
My Strains: Rename, Edit, Delete, Create Copy, Export
My Sequence: Rename, Edit, Delete, Create Copy, Export || Create Parts from Sequences, Create Parts from Sequence Features
My Amino Acid Sequence: Rename, Edit, Delete, Create Copy, Export
My Parts: Rename, Edit, Delete, Create Copy, Export
My Projects: Rename, Edit, Delete, Create Copy, Export

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#68
