### ISSUE TITLE
Design export/import broken for XML

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1412]
Try
1) creating an example design (SLIC/Gibson/CPEC for example)
2) exporting the design as an **XML file**
3) deleting the example design
4) importing the saved external XML design file (first image)
**5) open up the first element of the design (the vector backbone). It will be linear instead of circular and it's name will be ORGANISM instead of pBbs8c-RFP. (2nd image)**

![image](https://cloud.githubusercontent.com/assets/7561861/10182208/73613996-66d6-11e5-867d-d6e2158882ea.png)

![image](https://cloud.githubusercontent.com/assets/7561861/10182216/85b401f0-66d6-11e5-89ef-08d823b997bf.png)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#64
