### ISSUE TITLE
sequences attached to strains by name

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/ve#1422]
Before exporting a strain, any associated sequences are "attached" to the strain via name: 

```
                strains.forEach(function(strain) {
                    var plasmidNameArray = [];
                    strain.sequences.forEach(function(sequence) {
                        plasmidNameArray.push(sequence.name);
                    });
                    strain.plasmids = plasmidNameArray.join(",");
                });

```

This will fail if multiple sequences have the same name. We should instead be attaching the sequences to their respective strains in a different way, either by passing a "hash" of the sequence, or perhaps better yet, using a bit of extra meta-data to explicitly define which sequences go with which strains.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#40
