### ISSUE TITLE
Authentication Page Links and Functions

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1427]
Check all links and functions on Login page. Many are missing.
1) Active Directory Login
2) Registration Request
3) Forgot Password
4) External links need to be made internal
5) Local Login is working nicely... However "Check Email" notification pops up when a successful login has been achieved.... this may be because no valid email yet exists. Presumably this will get fixed with 1) above.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#39
