### ISSUE TITLE
Explorer and Library views... naming and action specification

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1429]
Rationalize explorer and corresponding tab naming and action conventions, particularly in light of the fact that we will be allowing two classes of data... Local ("My") data and Global ("Shared") data. Note that shared data is only populated based on users role and if an admin has allowed user to see said shared data.

*Indicates New Feature

**Tab Specification:**

Explorer Library Name | Tab Name | Tab Icon | Subtab Name(s)*
------------ | -------------|-----------|---------------|-------------|
Protocols |  Protocols | List Icon | "My Protocols", "Shared Protocols"
Strains    | Strains | Bacteria Icon  | "My Strains", "Shared Strains"
DNA Sequences | DNA Sequences | Circle Icon  | "My DNA Sequences", "Shared DNA Sequences
AA Sequences | AA Sequences | Triangle Icon  | "My AA Sequences", "Shared AA Sequences"

**Click Action Specification**

Explorer Library Name | Hover Over Action | Single Click Action | Double Click Action
------------ | -------------|-----------|---------------|
Protocols | Meta Data Summary* | None | Data view/edit screen
Strains    | Meta Data Summary* | None | Data view/edit screen
DNA Sequences | Meta Data Summary* | Mini view | Data view/edit screen*
AA Sequences | Meta Data Summary* | Mini view | Data view/edit screen*

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#38
