### ISSUE TITLE
Warning message not quite right for loading an example file.

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1433]
Warning message not quite right for loading an example design. An example file is not an imported design. Replace "imported design" with "example design". A further enhancement would be to drop this error message entirely when you are loading an example design into a newly created design canvas.

![image](https://cloud.githubusercontent.com/assets/7561861/10562547/7ad44b80-7515-11e5-9be8-42b5e2e95367.png)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#37
