### ISSUE TITLE
Can't import or create a valid FASTA AA file

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1438]
Can't import or create a valid FASTA AA file. Should be able to create in a simple text box editor for direct typing or cut/paste.
>gi|129295|sp|P01013|OVAX_CHICK GENE X PROTEIN (OVALBUMIN-RELATED) QIKDLLVSSSTDLDTTLVLVNAIYFKGMWKTAFNAEDTREMPFHVTKQESKPVQMMCMNNSFNVAT PAEKMKILELPFASGDLSMLVLLPDEVSDLERIE TINFEKLTEWTNPNTMEKRRVKVYLPQMKIEEK NLTSVLMALGMTDLFIPSANLTGISSAESLKISQ VHGAFMELSEDGIEMAGSTGVIEDIKHSPESEQ RADHPFLFLIKHNPTNTIVYFGRYWSP

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#35
