### ISSUE TITLE
Duplicate sequence warning is confusing to users

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1442]
As a user, I'm not sure what to do.... I'm not sure why it is even a problem. To me the user, it looks like a bug. (It may be a bug since my database has duplicate parts because delete parts is not working)

![image](https://cloud.githubusercontent.com/assets/7561861/10564653/a56f42b8-7570-11e5-90fd-fcffa5cd34a1.png)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#34
