### ISSUE TITLE
Design Editor Export/Import does not pick up imported file name

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1447]
Design Editor: Export/Import > JSON File
Design Editor: Export/Import > XML File

I exported a design, then reimported. I can't tell if it worked because I tried to distinguish the newly imported file by changing it's name. When I re-import, the same name appears as the one I exported... perhaps because it is picking up the design name from meta-data inside the file and not the file name. I'm not sure what the proper behavior should be, but this will be confusing to users who might expect that the file name will be the design name.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#33
