### ISSUE TITLE
VE SBOL export not functioning as expected

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#1453]
In VE if I export a sequence as SBOL, it takes a long time to do anything. It should provide a progress bar or some indicator to the user that it is doing something if it is going to take so long. Also, the resulting .zip is nonsense and doesn't contain the expected SBOL content. UI informs user that there was an error: "Encountered an error:" but is not specific as to what the problem was.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#31
