### ISSUE TITLE
VE Restriction Enzyme Manager - several problems

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#1456]
In VE, in Tools -> Restriction Enzymes Manager, there are several problems:

1) Built-in groups e.g. "Common Enzymes" are duplicated several times in Enzyme Groups list.

2) User-defined group saving is not working.

3) Rendered view of active enzymes is not sync'd with actual active enzymes list. For example, if I start with common enzymes active and turn on view cut sites, everything looks good. Then I go into the manager and remove all enzymes from the active group list and save. Still looks good. But, when go back to the manager, the manager suggests that the full common enzyme group is active, when nothing is active.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#103
