### ISSUE TITLE
Missing download button for existing server versions of j5 Master Lists

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1474]
Design Editor: Inspector > j5 > Basic > Master Lists
Missing download button for existing server versions of j5 Master Lists (Plasmid, Oligo, Synthesis).

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#24

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#25
