### ISSUE TITLE
My sequence library not automatically updated

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#1497]
If I open the sequence library on the my sequences tab, delete all of the sequences, open a design, and load a built in example design, the my sequences tab is not automatically updated with the new sequences. I either have to toggle between the peony sequences and back or close and reopen the sequence library to see the added seqeunces.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#95
