### ISSUE TITLE
Can not saved edited sequence imported with parts

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#1498]
If I import a sequence with parts, and then try to edit the sequence, I get a error saving parts message. This doesn't seem to affect sequences with parts that originated from built-in example designs. This may be related to ticket #1496.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#90

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#93

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#94
