### ISSUE TITLE
Can't save AA sequence from text input interface

### ISSUE THREAD

**Issue by mfero** [TeselaGen/ve#1534]
Can't save AA sequence from text input interface.
![screen shot 2015-10-30 at 7 44 52 pm](https://cloud.githubusercontent.com/assets/7561861/10861512/16acded6-7f3f-11e5-924b-1da8ac1e06ce.png)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#21
