### ISSUE TITLE
VE - annotate panel wrap highlighting around the origin

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#835]
In ticket #590 a few weeks ago, I learned that in the VE annotate panel there was a way to wrap the selection around the origin, essentially by clicking at any point in the sequence, holding down, dragging up, coming out of the annotate panel and into the map panel, and then re-entering the annotate panel below my original click starting point. I could also do this by dragging down, coming out, and re-entering above my entry point.

Now, I do not see this working for me anymore. When I re-enter the annotate panel, it just flips the highlight selection direction.

It was kind of cool to be able to have the functionality from before. Can we bring it back?

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#57

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#58
