### ISSUE TITLE
VE - when parts are displayed, not possible to select around origin in map panel

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#837]
To reproduce, in DE, open a CGG buit in example design, double click on the GFPuv part to open pj5_00001 in VE. If parts are displayed, you can no longer click and drag around the origin in the map panel. If I turn off parts display, I can click and drag around the origin just fine.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#56
