### ISSUE TITLE
Various drawing issues with amino acid frames

### ISSUE THREAD

**Issue by tnrich** [TeselaGen/ve#956]
parts and normal translations:
![image](https://cloud.githubusercontent.com/assets/2730609/7169533/390bd85c-e37b-11e4-95f8-cf5f3148b846.png)

orfs and and revcomp translations:
![image](https://cloud.githubusercontent.com/assets/2730609/7169551/665cce74-e37b-11e4-99da-abde5112cbfb.png)

rev-comp frames: looks like the first row draws the frames properly, but subsequent rows are shifted to the left.
![image](https://cloud.githubusercontent.com/assets/2730609/7169695/ba1e419a-e37c-11e4-92da-68dccb4843b9.png)
![image](https://cloud.githubusercontent.com/assets/2730609/7169703/cfdada52-e37c-11e4-8b37-b815e57ff488.png)

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#55
