### ISSUE TITLE
strain import from zip file broken on stage

### ISSUE THREAD

**Issue by njhillson** [TeselaGen/ve#972]
On stage now I can import fine from a strain library .csv file, but importing from a zip file that contains the .csv and a sequence subdirectory containing the referenced GenBank files does not work properly.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#53

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/Peony-Issue-Tracking#54
